name: CI

on:
  pull_request:
    branches: [master]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: |
            8
            22
            25
          cache: maven

      - name: Run Maven with Java 8
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_8_X64 }}
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn -B compile
      - name: Run Maven with Java 22
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_22_X64 }}
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn -B compile
      - name: Run Maven with Java 25
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_25_X64 }}
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn -B compile

      - name: Run test on Java 8
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_8_X64 }}
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn -B verify
      - name: Run test on Java 22
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_22_X64 }}
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn -B verify
      - name: Run Maven with Java 25
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_25_X64 }}
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn -B verify
